obj-$(CONFIG_TARGET_SERIES_CELOX) += celox/
obj-$(CONFIG_USB_SWITCH_FSA9480) += sec_switch.o
obj-$(CONFIG_BROADCOM_WIFI) += broadcom_wlan.o
obj-$(CONFIG_SEC_LOG_LAST_KMSG) += sec_last_log.o

obj-y += display/
