ccflags-y := -Iarch/arm/mach-msm

obj-$(CONFIG_TARGET_SERIES_CELOX) += celox/
obj-$(CONFIG_USB_SWITCH_FSA9480) += sec_switch.o
obj-$(CONFIG_BROADCOM_WIFI) += broadcom_wlan.o
obj-$(CONFIG_BT_BCM4330) += board-bluetooth-bcm4330.o
obj-$(CONFIG_SEC_LOG_LAST_KMSG) += sec_last_log.o

obj-y += display/

obj-$(CONFIG_MSM_SDIO_AL) += sdio_al.o
obj-$(CONFIG_MSM_SDIO_AL) += sdio_al_dloader.o
obj-$(CONFIG_MSM_SDIO_DMUX) += sdio_dmux.o
obj-$(CONFIG_MSM_SDIO_TTY) += sdio_tty.o
obj-$(CONFIG_MSM_SDIO_CMUX) += sdio_cmux.o
obj-$(CONFIG_MSM_SDIO_CTL) += sdio_ctl.o
obj-$(CONFIG_MSM_RPC_SDIO_XPRT) += rpcrouter_sdio_xprt.o
obj-$(CONFIG_MSM_SDIO_SMEM) += sdio_smem.o
